# Site settings
title: Pewen Blog
email: fnbellomo@gmail.com
description: "Pewen blog. Somos un grupo multidisiplinar, bajo la idea de la ciencia reproducible, que queremos compartir y/o debatir sobre temas como tecnología, TIC, ciencia, python, raspberry-pi, governanza de internet, política, sociedad, propiedad intelectual, entre varios temas."
encoding: utf-8

# Server
baseurl: "/blog"
url: "https://pewen.github.io"

# Time zone
timezone: America/Argentina/Cordoba

# Pagination
paginate: 4
paginate_path: "/page:num/"

# Build settings
exclude: [.git, .gitignore]

# Conversion
markdown: kramdown

# Outputting
permalink: pretty

# Social links
twitter_username: jekyllrb
github_username:  jekyll
